version: 0.0
os: linux
files:
  - source: /
    destination: /myapp
permissions:
  - object: /myapp/startApp.ss, /myapp/verify_service.sh
    mode: 777
hooks:
  ApplicationStart:
    - location: startApp.sh
      timeout: 10
  ValidateService:
    - location: verify_service.sh
      timeout: 20
